server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

      routes:
        - id: preflight
          uri: no://op  # 프리플라이트 요청에 대한 처리
          predicates:
            - Method=OPTIONS
          filters:
            - RemoveRequestHeader=Origin  # OPTIONS 요청에 Origin 헤더를 삭제

        - id: users
          uri: https://user.neon7.site
          predicates:
            - Path=/users/**
          filters:
            - JwtAuthenticationFilter
            - PreserveHostHeader  # Host 헤더 보존
            - AddRequestHeader=Authorization, "#{request.headers['Authorization']}"  # Authorization 헤더를 명시적으로 전달 (필요 시)

        - id: oauth2
          uri: https://user.neon7.site
          predicates:
            - Path=/oauth2/**

        - id: auth
          uri: https://user.neon7.site
          predicates:
            - Path=/auth/**

        - id: login
          uri: https://user.neon7.site
          predicates:
            - Path=/login/**

        - id: logout
          uri: https://user.neon7.site
          predicates:
            - Path=/logout/**

        - id: events-get
          uri: https://event.neon7.site
          predicates:
            - Path=/events/**
            - Method=GET

        - id: events-post-put-delete
          uri: https://event.neon7.site
          predicates:
            - Path=/events/**
            - Method=POST,PUT,DELETE
          filters:
            - JwtAuthenticationFilter

      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "https://neon7.site"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowCredentials: true
            allowedHeaders: "*"
            exposedHeaders: "*"

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

jwt:
  secret: ${JWT_SECRET}