spring:
  datasource:
    url: jdbc:mysql://localhost:3306/proddb
    username: siyoon
    password: 375632
  jpa:
    hibernate:
      ddl-auto: none

app:
  origins:
    - "https://neon7.site"
    - "https://www.neon7.site"