spring:
  application:
    name: chat
server:
  port: 8443 # Spring Boot? HTTPS? ???? ??
  ssl:
    key-store: classpath:keystore.p12  # ??? ??? ???? ?? ??
    key-store-password: 375632  # ???? ????
    keyStoreType: PKCS12  # ???? ??
    keyAlias: tomcat  # ?? ??(alias)