server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: https://user.neon7.site  # 인증 서비스로 라우팅
          predicates:
            - Path=/users/**
          filters:
            - JwtAuthenticationFilter  # JWT 필터 적용
        - id: event-service
          uri: https://event.neon7.site  # 이벤트 서비스로 라우팅
          predicates:
            - Path=/events/**
          filters:
            - JwtAuthenticationFilter  # JWT 필터 적용
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "https://neon7.site"
              - "https://www.neon7.site"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowCredentials: true
            allowedHeaders: "*"
            exposedHeaders: "*"

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

jwt:
  secret: vB2VcZBQRNRTd2KoLvjYx7UPJyYrJLcUOqdv59cob+w=