server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: preflight
          uri: no://op
          predicates:
            - Method=OPTIONS
          filters:
            - RemoveRequestHeader=Origin

        - id: users
          uri: https://user.neon7.site
          predicates:
            - Path=/users/**
          filters:
            - PreserveHostHeader

        - id: oauth2
          uri: https://user.neon7.site
          predicates:
            - Path=/oauth2/**

        - id: auth
          uri: https://user.neon7.site
          predicates:
            - Path=/auth/**

        - id: login
          uri: https://user.neon7.site
          predicates:
            - Path=/login/**

        - id: events-get
          uri: https://event.neon7.site
          predicates:
            - Path=/events/**
            - Method=GET

        - id: events-post-put-delete
          uri: https://event.neon7.site
          predicates:
            - Path=/events/**
            - Method=POST,PUT,DELETE

      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "https://neon7.site"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowCredentials: true
            allowedHeaders: "*"
            exposedHeaders: "*"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://your-issuer.com  # JWT 발급자 URL
          jwk-set-uri: https://your-issuer.com/.well-known/jwks.json  # JWK Set URI

jwt:
  secret: ${JWT_SECRET}

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  level:
    org.springframework.security: DEBUG
    com.neon.gateway: DEBUG